---
- hosts: googlemachines
  become: true
  tasks:
    - name: uninstall nginx on ubuntu
      apt: name=nginx state=latest
      when: ansible_os_family == "Debian"

    - name: uninstall nginx on centos
      yum: name=nginx state=latest
      when: ansible_os_family == "RedHat"