  
---
    - name: Playbook with variables demo
      hosts: googlemachines
      vars:
        - var1: zig
        - var2: zag
      tasks:
        - name: print data
          shell: echo "{{var1}} when you should {{var2}}" > /home/taimoor/vars.txt